# Generated by Django 5.2.15 on 2026-06-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_entityconfig_company_upi_id_paymentrecord_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='installment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('part', 'Part Payment / Installment')], default='full', max_length=20),
        ),
    ]
