# Generated by Django 4.2.7 on 2026-06-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_paymentrecord_installment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetissue',
            name='damage_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/damage_images/'),
        ),
        migrations.AddField(
            model_name='assetissue',
            name='damage_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
