# Generated by Django 4.2.7 on 2026-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_assetissue_damage_image_assetissue_damage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doc_aadhar_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_college_id_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_photo_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_resume_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
