# Generated by Django 4.2.7 on 2026-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_userprofile_doc_aadhar_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
    ]
