# Generated by Django 5.2.15 on 2026-06-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=500)),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='sims.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR/Behavioral'), ('mixed', 'Mixed'), ('project', 'Project-Based'), ('company', 'Company Prep')], default='technical', max_length=20)),
                ('difficulty', models.CharField(default='intermediate', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('questions_answers', models.JSONField(default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('report', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='sims.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AILearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_data', models.JSONField(default=dict)),
                ('progress', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='sims.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AIPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField(default=dict)),
                ('ai_score', models.FloatField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='sims.userprofile')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_content', models.JSONField(default=dict)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('evaluation_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_data', to='sims.userprofile')),
            ],
        ),
    ]
